# Generated by Django 3.2.9 on 2022-04-10 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicines',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('purchase_cost', models.FloatField()),
                ('selling_cost', models.FloatField()),
                ('description', models.CharField(max_length=500)),
                ('quantity', models.IntegerField()),
            ],
            options={
                'db_table': 'medicine',
            },
        ),
    ]
