# Generated by Django 3.2.9 on 2022-04-12 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicines',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('purchase_cost', models.FloatField()),
                ('selling_cost', models.FloatField()),
                ('description', models.CharField(max_length=500)),
                ('quantity', models.IntegerField()),
            ],
            options={
                'db_table': 'medicine',
            },
        ),
        migrations.CreateModel(
            name='SaledMedicine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Bill_number', models.CharField(max_length=100)),
                ('customer_name', models.CharField(max_length=50)),
                ('customer_phonenum', models.CharField(max_length=15)),
                ('quantity', models.IntegerField()),
                ('item_price', models.FloatField()),
                ('gst', models.FloatField()),
                ('grand_total', models.FloatField()),
                ('medicines', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.medicines')),
            ],
            options={
                'db_table': 'sellings',
            },
        ),
    ]
