# Generated by Django 3.2.9 on 2022-04-12 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_saledmedicine'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saledmedicine',
            old_name='Medicines',
            new_name='medicines',
        ),
    ]
